# -*- coding: utf-8 -*-
"""Копия блокнота "модель_сегментация-объектов.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDJgRiJFV4FLOuciwIj5971v9Sb93DfJ

# 2 версия
"""

from google.colab import drive
drive.mount('/content/drive')

import os
from glob import glob

TRAIN_IMG_DIR = "/content/drive/MyDrive/data/train/image"
TRAIN_MASK_DIR = "/content/drive/MyDrive/data/train/label"

VAL_IMG_DIR = "/content/drive/MyDrive/data/val/image"
VAL_MASK_DIR = "/content/drive/MyDrive/data/val/label"

print("Train images:", len(glob(TRAIN_IMG_DIR + "/*.npy")))
print("Train masks:", len(glob(TRAIN_MASK_DIR + "/*.npy")))
print("Val images:", len(glob(VAL_IMG_DIR + "/*.npy")))
print("Val masks:", len(glob(VAL_MASK_DIR + "/*.npy")))

# Пример вывода нескольких файлов для проверки
print("Train images sample:", glob(TRAIN_IMG_DIR + "/*.npy")[:5])
print("Train masks sample:", glob(TRAIN_MASK_DIR + "/*.npy")[:5])

import torch
import numpy as np
import albumentations as A
from albumentations.pytorch import ToTensorV2
from torch.utils.data import DataLoader
from glob import glob
import os
from tqdm import tqdm
import segmentation_models_pytorch as smp

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
BATCH_SIZE = 4
NUM_CLASSES = 19
LR = 1e-3
EPOCHS = 25

"""Шаг 4. Определение аугментаций и датасета"""

train_transform = A.Compose([
    A.Resize(256, 512),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    ToTensorV2(),
])

val_transform = A.Compose([
    A.Resize(256, 512),
    ToTensorV2(),
])

class SegmentationDataset(torch.utils.data.Dataset):
    def __init__(self, image_dir, mask_dir, transform):
        self.image_paths = sorted(glob(os.path.join(image_dir, '*.npy')))
        self.mask_paths = sorted(glob(os.path.join(mask_dir, '*.npy')))
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = np.load(self.image_paths[idx]).astype(np.uint8)
        mask = np.load(self.mask_paths[idx]).astype(np.uint8)
        mask[mask == 255] = 0  # 🛠️ заменяем "ignore" на фон

        augmented = self.transform(image=image, mask=mask)
        image = augmented['image'].float() / 255.0  # 🔄 нормализация в [0,1]
        mask = augmented['mask']

        return image, mask.long()

"""Шаг 5. Создание датасетов и загрузчиков с проверкой размеров"""

train_dataset = SegmentationDataset(TRAIN_IMG_DIR, TRAIN_MASK_DIR, train_transform)
val_dataset = SegmentationDataset(VAL_IMG_DIR, VAL_MASK_DIR, val_transform)

print("Train dataset size:", len(train_dataset))
print("Validation dataset size:", len(val_dataset))

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, num_workers=0)

"""Шаг 6. Определение модели, оптимизатора, функции потерь и lr_scheduler"""

model = smp.Unet(encoder_name="resnet34", encoder_weights="imagenet", classes=NUM_CLASSES, activation=None).to(DEVICE)
loss_fn = smp.losses.DiceLoss(mode='multiclass')
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

"""Шаг 7. Определение функций обучения и валидации"""

def train_one_epoch(loader, model, optimizer, loss_fn):
    model.train()
    epoch_loss = 0
    for images, masks in tqdm(loader):
        print(images.dtype, images.shape)
        print(masks.dtype, masks.shape)
        images = images.to(DEVICE)
        masks = masks.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss = loss_fn(outputs, masks)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    return epoch_loss / len(loader)


def evaluate(loader, model, loss_fn):
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for images, masks in loader:
            images = images.to(DEVICE)
            masks = masks.to(DEVICE).long()  # и тут тоже
            outputs = model(images)
            loss = loss_fn(outputs, masks)
            val_loss += loss.item()
    return val_loss / len(loader)

"""Шаг 8. Запуск обучения"""

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(train_loader, model, optimizer, loss_fn)
    val_loss = evaluate(val_loader, model, loss_fn)
    scheduler.step()
    print(f"Epoch {epoch+1}/{EPOCHS}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

# После окончания обучения сохраняем модель
torch.save(model.state_dict(), "esnet_segmentation.pth")

"""# Тут будет слишком долгое обучение, облегчим параметры"""

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
BATCH_SIZE = 2
NUM_CLASSES = 19
LR = 1e-3
EPOCHS = 3

"""2. Аугментации (с уменьшенным разрешением)"""

train_transform = A.Compose([
    A.Resize(128, 256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    ToTensorV2(),
])

val_transform = A.Compose([
    A.Resize(128, 256),
    ToTensorV2(),
])

"""3. Dataset с ограничением на 300 файлов"""

class SegmentationDataset(torch.utils.data.Dataset):
    def __init__(self, image_dir, mask_dir, transform):
        self.image_paths = sorted(glob(os.path.join(image_dir, '*.npy')))[:300]
        self.mask_paths = sorted(glob(os.path.join(mask_dir, '*.npy')))[:300]
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = np.load(self.image_paths[idx]).astype(np.uint8)
        mask = np.load(self.mask_paths[idx]).astype(np.uint8)
        mask = np.clip(mask, 0, NUM_CLASSES - 1)  # важно
        augmented = self.transform(image=image, mask=mask)
        image = augmented['image']
        mask = augmented['mask']
        return image.float(), mask.long()

train_dataset = SegmentationDataset(TRAIN_IMG_DIR, TRAIN_MASK_DIR, train_transform)
val_dataset = SegmentationDataset(VAL_IMG_DIR, VAL_MASK_DIR, val_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, num_workers=2)

model = smp.FPN(encoder_name="resnet18", classes=NUM_CLASSES, activation=None).to(DEVICE)
loss_fn = smp.losses.DiceLoss(mode='multiclass')
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

def train_one_epoch(loader, model, optimizer, loss_fn):
    model.train()
    epoch_loss = 0
    for i, (images, masks) in enumerate(tqdm(loader)):
        images, masks = images.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss = loss_fn(outputs, masks)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        if i % 50 == 0:
            print(f"[Batch {i}/{len(loader)}] Loss: {loss.item():.4f}")
    return epoch_loss / len(loader)

def evaluate(loader, model, loss_fn):
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for images, masks in loader:
            images, masks = images.to(DEVICE), masks.to(DEVICE)
            outputs = model(images)
            loss = loss_fn(outputs, masks)
            val_loss += loss.item()
    return val_loss / len(loader)

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(train_loader, model, optimizer, loss_fn)
    val_loss = evaluate(val_loader, model, loss_fn)
    scheduler.step()
    print(f"Epoch {epoch+1}/{EPOCHS} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

torch.save(model.state_dict(), "segmentation_model.pth")